spring:
  datasource:
    username: root
    password: xqs123456
    url: jdbc:mysql://localhost:3306/codingmore-mysql?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
  jpa:
    show-sql: true
  thymeleaf:
    cache: false # 开发时关闭缓存，不然看不到实时页面